version: 2
registries:
  hex-organization-oban:
    type: hex-organization
    organization: oban
    key: "${{secrets.HEX_ORGANIZATION_OBAN_KEY}}"

updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  target-branch: main
  ignore:
  - dependency-name: timex
    versions:
    - 3.7.3
  registries:
  - hex-organization-oban
